# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16Y_pGP7YajqEn7PfFpzsIRqOTOZ129oQ
"""

import pandas as pd
import numpy as np

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

print("Libraries Imported Successfully ✅")

courses = {
    "Course": [
        "Python Programming",
        "Machine Learning",
        "Artificial Intelligence",
        "Data Science",
        "Deep Learning",
        "Web Development",
        "Java Programming",
        "Cyber Security",
        "Cloud Computing",
        "Android Development"
    ],

    "Skills": [
        "python coding programming",
        "python machine learning ai",
        "artificial intelligence ai python",
        "python pandas numpy data analysis",
        "deep learning tensorflow keras ai",
        "html css javascript web",
        "java oop programming",
        "network hacking security",
        "aws azure cloud",
        "android java kotlin"
    ]
}

import pandas as pd

df = pd.DataFrame(courses)

df.to_csv("courses.csv", index=False)

print(df)

df = pd.read_csv("courses.csv")

df.head()

vectorizer = TfidfVectorizer()

tfidf_matrix = vectorizer.fit_transform(df["Skills"])

print(tfidf_matrix.shape)

user_interest = input("Enter your interest: ")

# User interest ko TF-IDF me convert karo
user_vector = vectorizer.transform([user_interest])

# Similarity calculate karo
similarity = cosine_similarity(user_vector, tfidf_matrix)

# Top 5 recommendations
top_indices = similarity.argsort()[0][-5:][::-1]

print("\nRecommended Courses:\n")

for index in top_indices:
    print(df.iloc[index]["Course"])
    print("Similarity Score:", round(similarity[0][index]*100,2), "%")
    print("-"*40)